dependencies {
    api project(":libai-core")
    // pinyin
    api 'io.github.biezhi:TinyPinyin'
    // oss
    api 'com.aliyun.oss:aliyun-sdk-oss'
    // sms
    api 'com.aliyun:dysmsapi20170525'
    api 'com.aliyun:openapiutil'
    // 腾讯云
    api 'com.tencentcloudapi:tencentcloud-sdk-java'
    // easy poi
    api 'cn.afterturn:easypoi-base'
    api 'cn.afterturn:easypoi-web'
    api 'cn.afterturn:easypoi-annotation'
    // jwt
    api 'io.jsonwebtoken:jjwt-api'
    api 'io.jsonwebtoken:jjwt-impl'
    api 'io.jsonwebtoken:jjwt-jackson'
}
