dependencies {
    api project(":libai-core")
    api "com.google.guava:guava"
    api 'org.springframework.boot:spring-boot-starter-web'
    // jackson jsr310 日期时间模块
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    // redis
    api "org.apache.commons:commons-pool2"
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    // 密码
    api 'org.springframework.security:spring-security-crypto'
    // mybatis
    api 'com.baomidou:mybatis-plus-spring-boot3-starter'
    api 'com.baomidou:mybatis-plus-jsqlparser'
    api 'com.alibaba:druid-spring-boot-starter'
    api 'com.mysql:mysql-connector-j'
}
