plugins {
    id 'org.springframework.boot'
}

tasks.bootJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// 禁用 plain jar，只保留 Spring Boot 可执行 jar
tasks.named('jar') {
    enabled = false
}

dependencies {
    api project(":libai-boot")
    api project(":libai-provider")
    api 'org.springframework.boot:spring-boot-starter-actuator'
    api 'io.micrometer:micrometer-registry-prometheus'
}
