dependencies {
    api "at.favre.lib:bcrypt"
    api 'org.apache.commons:commons-collections4'
    api 'org.apache.commons:commons-lang3'
    api "com.squareup.okhttp3:okhttp"
    api 'org.modelmapper:modelmapper'
    api 'org.slf4j:slf4j-api'
    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'com.fasterxml.jackson.core:jackson-annotations'
    api 'com.fasterxml.jackson.core:jackson-core'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}