dependencies {
    api project(":libai-common")
    api "com.google.guava:guava"
    api 'org.springframework.boot:spring-boot-starter'
    api "org.springframework.boot:spring-boot-starter-validation"
    // redis
    api "org.apache.commons:commons-pool2"
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    // mybatis
    api 'com.baomidou:mybatis-plus-spring-boot3-starter'
    api 'com.baomidou:mybatis-plus-jsqlparser'
    api 'com.alibaba:druid-spring-boot-3-starter'
    api 'com.mysql:mysql-connector-j'
}